[package]
name = "connector"
version = "0.1.0"
edition = "2021"



[dependencies]
log = "0.4"
env_logger = "0.10.1"
tokio = { version = "1.35.1", features = ["full"] }
tiktoklive = "0.0.18"
serde_json = "1.0.127"
